# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HesapMakinesi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_birinci_sayi = QtWidgets.QLabel(self.centralwidget)
        self.label_birinci_sayi.setGeometry(QtCore.QRect(100, 90, 101, 51))
        self.label_birinci_sayi.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_birinci_sayi.setObjectName("label_birinci_sayi")
        self.label_ikinci_sayi = QtWidgets.QLabel(self.centralwidget)
        self.label_ikinci_sayi.setGeometry(QtCore.QRect(100, 180, 101, 51))
        self.label_ikinci_sayi.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_ikinci_sayi.setObjectName("label_ikinci_sayi")
        self.lineEdit_birinci_sayi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_birinci_sayi.setGeometry(QtCore.QRect(180, 100, 181, 31))
        self.lineEdit_birinci_sayi.setObjectName("lineEdit_birinci_sayi")
        self.lineEdit_ikinci_sayi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ikinci_sayi.setGeometry(QtCore.QRect(180, 190, 181, 31))
        self.lineEdit_ikinci_sayi.setObjectName("lineEdit_ikinci_sayi")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 260, 395, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_toplama = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_toplama.setObjectName("pushButton_toplama")
        self.horizontalLayout.addWidget(self.pushButton_toplama)
        self.pushButton_cikarma = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_cikarma.setObjectName("pushButton_cikarma")
        self.horizontalLayout.addWidget(self.pushButton_cikarma)
        self.pushButton_carpma = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_carpma.setObjectName("pushButton_carpma")
        self.horizontalLayout.addWidget(self.pushButton_carpma)
        self.pushButton_bolme = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_bolme.setObjectName("pushButton_bolme")
        self.horizontalLayout.addWidget(self.pushButton_bolme)
        self.label_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.label_sonuc.setGeometry(QtCore.QRect(100, 370, 101, 51))
        self.label_sonuc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_sonuc.setObjectName("label_sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_birinci_sayi.setText(_translate("MainWindow", "Birinci Sayı:"))
        self.label_ikinci_sayi.setText(_translate("MainWindow", "İkinci Sayı:"))
        self.pushButton_toplama.setText(_translate("MainWindow", "TOPLAMA"))
        self.pushButton_cikarma.setText(_translate("MainWindow", "ÇIKARMA"))
        self.pushButton_carpma.setText(_translate("MainWindow", "ÇARPMA"))
        self.pushButton_bolme.setText(_translate("MainWindow", "BÖLME"))
        self.label_sonuc.setText(_translate("MainWindow", "Sonuç:"))
